// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDxlND__vmvfnbCKy_g01acAtpIFE3WJA',
    appId: '1:702969521148:web:853093292d61b6f8e30879',
    messagingSenderId: '702969521148',
    projectId: 'schoolapp-b79f4',
    authDomain: 'schoolapp-b79f4.firebaseapp.com',
    storageBucket: 'schoolapp-b79f4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuBFoJRJiapLQVB9aicMrzv-Uk4JSBYZ0',
    appId: '1:702969521148:android:9799d23d4d85707ee30879',
    messagingSenderId: '702969521148',
    projectId: 'schoolapp-b79f4',
    storageBucket: 'schoolapp-b79f4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKxr87hxNmF1NGdTJIIPrIowOCXEM28bU',
    appId: '1:702969521148:ios:7ae3347dbf3e9533e30879',
    messagingSenderId: '702969521148',
    projectId: 'schoolapp-b79f4',
    storageBucket: 'schoolapp-b79f4.firebasestorage.app',
    iosBundleId: 'com.example.studentApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKxr87hxNmF1NGdTJIIPrIowOCXEM28bU',
    appId: '1:702969521148:ios:7ae3347dbf3e9533e30879',
    messagingSenderId: '702969521148',
    projectId: 'schoolapp-b79f4',
    storageBucket: 'schoolapp-b79f4.firebasestorage.app',
    iosBundleId: 'com.example.studentApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBDxlND__vmvfnbCKy_g01acAtpIFE3WJA',
    appId: '1:702969521148:web:90adbdb20d1e3b32e30879',
    messagingSenderId: '702969521148',
    projectId: 'schoolapp-b79f4',
    authDomain: 'schoolapp-b79f4.firebaseapp.com',
    storageBucket: 'schoolapp-b79f4.firebasestorage.app',
  );
}
